apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  MONGO_URI : mongodb+srv://admin:Aloo2001@namastenode.7bibinv.mongodb.net/Hire?appName=NamasteNode
  JWT_SECRET: supersecretkey